### ISSUE TITLE
[Request/Feature Suggestion] Add Support for BSP38

### ISSUE THREAD

**Issue by StroggVorbis** [UnrealKaraulov/newbspguy#101]
I wanted to ask if it's possible to add support for BSP38, the format used by Quake 2, Kingpin: Life of Crime and maybe some more games such as Soldier of Fortune. Unfortunately, I'm not a coder so I'm unable to assist in helping add this, but here's a documentation on the format which might be helpful and of interest to you.

https://www.flipcode.com/archives/Quake_2_BSP_File_Format.shtml

Let me know what you think :)

**Comment by UnrealKaraulov** [comment]
> I wanted to ask if it's possible to add support for BSP38, the format used by Quake 2, Kingpin: Life of Crime and maybe some more games such as Soldier of Fortune. Unfortunately, I'm not a coder so I'm unable to assist in helping add this, but here's a documentation on the format which might be helpful and of interest to you.
> 
> https://www.flipcode.com/archives/Quake_2_BSP_File_Format.shtml
> 
> Let me know what you think :)

It's possible, but I work alone on updates and I don't have enough time and desire to do everything. I'll leave this issue opened for future.

**Comment by SirYodaJedi** [comment]
While it'd be lovely to have, I have a feeling BSP38 would be a significant undertaking; collision works completely differently, using actual brush data instead of clipnodes (this is why it's much cleaner to decompile Quake II+Source 1 maps than Quake I+GoldSrc maps). Something more directly similar to Q1 BSP29, such as Hexen II BSP29, would be less complicated to implement [see isHexen2 function from ericw-tools](../../../ericwa/ericw-tools/blob/brushbsp/common/bspfile.cc).

**Comment by UnrealKaraulov** [comment]
Я не буду добавлять данный формат, нет желания и свободного времени, если кто-то захочет в pull request, я непротив.
